const API = 'http://localhost:8000';
const $ = id => document.getElementById(id);
async function api(path, options={}) { const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options}); const body=await r.json(); if(!r.ok) throw new Error(JSON.stringify(body)); return body; }
async function health(){try{await api('/health');$('health').textContent='API Connected';}catch(e){$('health').textContent='API Offline';}}
function formData(form){return Object.fromEntries(new FormData(form).entries())}
$('shipmentForm').onsubmit=async e=>{e.preventDefault();try{const f=formData(e.target);const body={shipment_id:f.shipment_id,origin:f.origin,destination:f.destination,cargo_type:f.cargo_type,quantity:Number(f.quantity),unit:f.unit,priority:f.priority,requested_delivery:f.requested_delivery,route:{route_id:f.route_id,estimated_travel_time_minutes:Number(f.travel_time),route_risk:Number(f.route_risk)}};$('shipmentResult').textContent=JSON.stringify(await api('/api/v1/shipments',{method:'POST',body:JSON.stringify(body)}),null,2);loadShipments();}catch(err){$('shipmentResult').textContent=err.message}};
$('shortageForm').onsubmit=async e=>{e.preventDefault();try{const f=formData(e.target);const body={district_id:f.district_id,district_name:f.district_name,product_type:f.product_type,current_inventory_units:Number(f.inventory),average_daily_consumption:Number(f.consumption),incoming_quantity_units:Number(f.incoming),incoming_eta_days:Number(f.incoming_eta),road_risk:Number(f.road_risk),population:Number(f.population)};$('shortageResult').textContent=JSON.stringify(await api('/api/v1/predictions/shortage',{method:'POST',body:JSON.stringify(body)}),null,2);}catch(err){$('shortageResult').textContent=err.message}};
$('warehouseForm').onsubmit=async e=>{e.preventDefault();try{const f=formData(e.target);const body={product_type:f.product_type,warehouses:[{warehouse_id:f.wh1,location:f.loc1,available_units:Number(f.units1)},{warehouse_id:f.wh2,location:f.loc2,available_units:Number(f.units2)}],target_districts:[{district_id:'DIST_001',demand_units:Number(f.demand),shortage_probability:Number(f.probability)}]};$('warehouseResult').textContent=JSON.stringify(await api('/api/v1/warehouses/optimize',{method:'POST',body:JSON.stringify(body)}),null,2);}catch(err){$('warehouseResult').textContent=err.message}};
async function loadShipments(){try{const rows=await api('/api/v1/shipments');$('shipments').innerHTML=rows.map(x=>`<tr><td>${x.shipment_id}</td><td>${x.priority}</td><td>${x.route_id}</td><td>${x.shipment_risk}</td><td>${x.status}</td><td>${new Date(x.estimated_arrival).toLocaleString()}</td></tr>`).join('');}catch(e){$('shipments').innerHTML='<tr><td colspan="6">Start the P5 API first.</td></tr>'}}
$('refresh').onclick=loadShipments; health(); loadShipments();
